#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
#

# Goal
#   1. Find scripts location
#   2. Find the other scripts around it
#   3. And call them

# Procedure
#   1. Find the script current name and location
#   2. Determine if it is a softlink
#   3. Find Target for softlink
#   4. Get the directory
#
# 1.
export TEST_FILE_LOCATION="${BASH_SOURCE[0]}"

# 2. /usr/local/bin/newfeature
export IS_SOFTLINK="NO"
[[ -s "${TEST_FILE_LOCATION}" ]] && IS_SOFTLINK="YES"

export FOUND_DIR_JOURNAL
# 3. Find Target for softlink
if [[ "${IS_SOFTLINK}" == "YES" ]] ; then
{
  # Here find command will break finding the soft link
  # shellcheck disable=SC2012
  FOUND_DIR_JOURNAL_SCRIPT="$(ls -l "${TEST_FILE_LOCATION}" | awk '{print $11}')" # Find target symlink, awk print 11 will split spaces and give you the 11th row in this case the softlink is spected
}
fi

# Tip How to find a dir on a script REF: https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within

# 4. Get the directory
FOUND_DIR_JOURNAL=$(dirname "${FOUND_DIR_JOURNAL_SCRIPT}")
# shellcheck disable=SC2001
FOUND_DIR_JOURNAL="$(sed 's/ /\\ /g' <<<"${FOUND_DIR_JOURNAL}")" # escape spaces
#test:   asserts that the result should equal at the location of the journal_intuivo_cli folder
#echo $FOUND_DIR_JOURNAL;


# tip
# set working directory as the scripts location during the execution of script
# un comment to pin to a specific dir
# comment out and allow to work globally
# cd "$(dirname "$0")"