#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
# journal_get_branch_merge_against

. $FOUND_DIR_JOURNAL/journal_get_extract_something_trimmed_between
. $FOUND_DIR_JOURNAL/journal_get_current_branch

#
# BRANCH_MERGE_AGAINST - Get branch MERGE AGAINST ..start
#
  echo -e "${blue23} • ${blue30} Get branch MERGE AGAINST  ${reset}"


  # Saved on git description from ${TARGETBASEBRANCH} _BASEBRANCH_";
  BRANCH_MERGE_AGAINST=$(git config branch.${CURBRANCH}.description | extract_something_trimmed_between "from" "_BASEBRANCH_");   # try git config description "from" branch_name ".BASEBRANCH."


  #?empty still  --look into .description
  if [[ -z "${BRANCH_MERGE_AGAINST}" ]]  && [ -f .description ] ; then                                                      # try cat .description "from" branch_name ".BASEBRANCH.")
    # Saved on .description?
    BRANCH_MERGE_AGAINST=$(extract_something_trimmed_between "from" "_BASEBRANCH_" --file .description);
  fi

  #?empty still  --look into .gitignore
  if [[ -z "${BRANCH_MERGE_AGAINST}" ]] && [ -f .gitignore ] ; then                                                         # try .gitignore #BRANCH-MERGE-AGAINST:branch_name
    # Saved on .gitignore?
    BRANCH_MERGE_AGAINST=$(cat .gitignore | grep "#BRANCH-MERGE-AGAINST:" | cut -d':' -f2)
  fi

  #?empty still   --default to 'develop'
  if [[ -z "${BRANCH_MERGE_AGAINST}" ]] ; then                                                                              # default to BRANCH-MERGE-AGAINST
    {
      BRANCH_MERGE_AGAINST="develop"
      msg_warning "    -  branch against defaulting to:${BRANCH_MERGE_AGAINST}"
    }
  fi
  msg_quote "branch against|${BRANCH_MERGE_AGAINST}"

  # TODO Saved on a file in .journal file inside the journal/project folder? TODO

#
# BRANCH_MERGE_AGAINST - Get branch MERGE AGAINST ..end
#

