#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
#

# TODO . TO have this in an options box
JOURNAL_HOME="/Users/Sites" # <-- I used for mac
JOURNAL_HOME="${HOME}/Sites" # <-- I used for mac
JOURNAL_HOME="/_" # <-- I used for mac

CURRENTDATE=`date +%Y%m%d`
CURRENT_LONG_DATE=`date`

JOURNAL_PROJECT_WORKING_ON=${PWD}

function msg_bullet() {
	echo -e "${blue23} • ${blue30} ${@} ${reset}"
}
function msg_error() {
	echo -e "${red} ERROR ! ${@} ${reset}"
}
function msg_warning() {
	echo -e "${yellow220} WARNING ! ${@} ${reset}"
}

JOURNAL_DEBUG_PROCESS=0
[[ "${@}" == *"--debug"* ]] && JOURNAL_DEBUG_PROCESS=1
(( $JOURNAL_DEBUG_PROCESS )) &&
(( $JOURNAL_DEBUG_PROCESS )) && echo -e "${voilet}JOURNAL_DEBUG_PROCESS${yellow220}:${green} ON ${yellow220}== ${blue32}${JOURNAL_DEBUG_PROCESS} ${yellow220}:"
