#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
#

# Remove white space REF: http://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable
function slash_to_underdash {
    sed 's/\//\_/g'
}
function single_quote_to_underdash {
   sed "s/'/\_/g"
}
function house_to_underdash {
    sed 's/\^/\_/g'
}
function ae_to_underdash {
    sed 's/\ä/\_/g'
}
function oe_to_underdash {
    sed 's/\ö/\_/g'
}
function ue_to_underdash {
    sed 's/\ü/\_/g'
}
function ss_to_underdash {
    sed 's/\ß/\_/g'
}
function money_to_underdash {
    sed 's/\$/\_/g'
}
function equal_to_underdash {
    sed 's/\=/\_/g'
}
function plus_to_underdash {
    sed 's/\+/\_/g'
}
function double_quotes_to_underdash {
    sed 's/\"/\_/g'
}
function commas_to_underdash {
    sed 's/\,/\_/g'
}
function common_to_underdash {
    sed 's/\:/\_/g'
}
function semicommon_to_underdash {
    sed 's/\;/\_/g'
}
function spaces_to_underdash {
    sed 's/\ /\_/g'
}
function remove_double_underdash {
    sed 's/__/\_/g' | sed 's/__/\_/g'
}
function squared_braket_open_to_underdash {
    sed "s/\[/\_/g"
}
function squared_braket_close_to_underdash {
    sed "s/\]/\_/g"
}
function remove_starting_underdash {
    sed 's/^\(\_\)*//'
}
function remove_last_underdash {
    sed 's/\_$//'
}
function cut_only_35 {
    cut -c 1-35
}
function spaces_to_newlines() {
    sed 's/ /\n/g'
}
function underdash_to_newlines() {
    sed 's/\_/\n/g'
}
function limit_words {
    local LIMIT=$1
    local COUNTER=0
    local COMBINED=''
    while read -r one_word; do
    {
        COMBINED="${COMBINED} ${one_word}"
        (( COUNTER++ ))
        if [ $COUNTER -eq $LIMIT ]; then
          echo "${COMBINED}"
          exit
        fi
    }
    done <<< "$(underdash_to_newlines)"
}
function use_5_words {
    limit_words 5 """${@}"""
}
function use_7_words {
    limit_words 7 """${@}"""
}
function dash_to_underdash {
    sed 's/\-/\_/g'
}
function convert_to_underdash {
   ae_to_underdash \
 | dash_to_underdash \
 | oe_to_underdash \
 | ue_to_underdash \
 | ss_to_underdash \
 | semicommon_to_underdash \
 | common_to_underdash \
 | spaces_to_underdash \
 | house_to_underdash \
 | money_to_underdash \
 | equal_to_underdash \
 | plus_to_underdash \
 | single_quote_to_underdash \
 | double_quotes_to_underdash \
 | slash_to_underdash \
 | commas_to_underdash \
 | squared_braket_open_to_underdash \
 | squared_braket_close_to_underdash \
 | remove_double_underdash \
 | remove_starting_underdash \
 | remove_last_underdash
}
function underscore_to_dash {
    sed "s/\_/\-/g"
}
function underscore_to_space {
    sed "s/\_/ /g"
}
function convert_to_lowercase {
    sed 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'
}
function convert_to_dash {
    convert_to_underdash \
  | underscore_to_dash
}
function convert_to_35_dashed {
    convert_to_underdash \
  | cut_only_35 \
  | underscore_to_dash \
  | remove_last_underdash
}
function only_5_dashed_words {
    convert_to_underdash \
  | use_5_words \
  | spaces_to_underdash \
  | remove_starting_underdash \
  | remove_last_underdash \
  | underscore_to_dash
}
function only_7_dashed_words {
    convert_to_underdash \
  | use_7_words \
  | spaces_to_underdash \
  | remove_starting_underdash \
  | remove_last_underdash \
  | underscore_to_dash
}
function escape_spaces {
    sed 's/\ /\\\ /g'
}
function escape_slashes {
    sed 's/\//\\\//g'
}
function escape_quotes {
    sed 's/\"/\\\"/g'
}

function change_line {
    local OLD_LINE_PATTERN=$1; shift
    local NEW_LINE=$1; shift
    local FILE=$1

    local NEW=$(echo "${NEW_LINE}" | escape_slashes)
    sed -i .bak '/'"${OLD_LINE_PATTERN}"'/s/.*/'"${NEW}"'/' "${FILE}"
    mv "${FILE}.bak" /tmp/
}
function pause(){
	# REF http://www.cyberciti.biz/tips/linux-unix-pause-command.html
   read -p "$*"
}
