#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
#

# Remove white space REF: http://stackoverflow.com/questions/369758/how-to-trim-whitespace-from-a-bash-variable
function slash_to_underdash {
    sed 's/\//\_/g'
}
function house_to_underdash {
    sed 's/\^/\_/g'
}
function ae_to_underdash {
    sed 's/\ä/\_/g'
}
function oe_to_underdash {
    sed 's/\ö/\_/g'
}
function ue_to_underdash {
    sed 's/\ü/\_/g'
}
function ss_to_underdash {
    sed 's/\ß/\_/g'
}
function money_to_underdash {
    sed 's/\$/\_/g'
}
function equal_to_underdash {
    sed 's/\=/\_/g'
}
function quotes_to_underdash {
    sed 's/\"/\_/g'
}
function commas_to_underdash {
    sed 's/\,/\_/g'
}
function spaces_to_underdash {
    sed 's/\ /\_/g'
}
function remove_double_underdash {
    sed 's/__/\_/g'
}
function convert_to_underdash {
   ae_to_underdash \
 | oe_to_underdash \
 | ue_to_underdash \
 | ss_to_underdash \
 | spaces_to_underdash \
 | house_to_underdash \
 | money_to_underdash \
 | equal_to_underdash \
 | quotes_to_underdash \
 | slash_to_underdash \
 | commas_to_underdash \
 | remove_double_underdash
}
function escape_spaces {
    sed 's/\ /\\\ /g'
}
function escape_slashes {
    sed 's/\//\\\//g'
}
function escape_quotes {
    sed 's/\"/\\\"/g'
}

function change_line {
    local OLD_LINE_PATTERN=$1; shift
    local NEW_LINE=$1; shift
    local FILE=$1

    local NEW=$(echo "${NEW_LINE}" | escape_slashes)
    sed -i .bak '/'"${OLD_LINE_PATTERN}"'/s/.*/'"${NEW}"'/' "${FILE}"
    mv "${FILE}.bak" /tmp/
}
function pause(){
	# REF http://www.cyberciti.biz/tips/linux-unix-pause-command.html
   read -p "$*"
}