#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
#

#
# DESCRIPTION GET - start
#
    # Empty description ?
    if [[ -z "${DESCRIPTION}"  ]] ; then
      # show all branches
      echo " "
        msg_error "No description. Need description ${reset}"
        echo "  USE:     ${THISSCRIPTNAME} \"Fix url issue\"         --- for example to fix "
        echo " "
      exit 1;
    fi

#
# DESCRIPTION GET - end
#

