#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
#
    #
    # CURBRANCH - start
    #
      # Get the current branch name into a variable
      #CURBRANCH=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')   # wrong output   TO-229
      #echo -e "${blue23} • ${blue30} Get current branch name  "
      CURBRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')          # correct output feature/TO-229
      
    #
    # CURBRANCH - end
    #

CURRENTDATE=$(date +%Y%m%d)
