#!/bin/bash #dependency
# package:journal_cli
# @author Zeus Intuivo <zeus@intuivo.com>
# journal_get_description_construct_the_description_assembly

[[ -z "${USER_OPENED_TICKET}" ]] &&  USER_OPENED_TICKET=${SUDO_USER}
[[ -z "${USER_OPENED_TICKET}" ]] &&  USER_OPENED_TICKET=${USER}

    # shellcheck disable=SC2154
    ONELINEDESCRIPTION="${DESCRIPTION}  ${blue33}  ${CURRENTDATE}  ${green} ‡ ${ISSUETRACKERLOCATION}"
    # shellcheck disable=SC2154
    ONELINEDESCRIPTION="${ONELINEDESCRIPTION} ${reset}  ${USER_OPENED_TICKET}  opened  ${green}  $(date)  ${gray238} ${FILENAME_FOR_DESCRIPTION_ASSEMBLY} "
    ONELINEDESCRIPTION="${ONELINEDESCRIPTION} from ${TARGETBASEBRANCH} _BASEBRANCH_";

